An example of a correctly formatted submission for this challenge (with a random number provided as predictions for SalePrice. Please ensure that your submission to Kaggle matches this format.

In [2]:
import pandas as pd

In [3]:
sample_housing = pd.read_csv('/Users/samconnelly/Downloads/sample_sub_reg.csv')

In [4]:
sample_housing

       Id    SalePrice
0       2  181479.1217
1       4  181479.1217
2       6  181479.1217
3       7  181479.1217
4      17  181479.1217
5      18  181479.1217
6      22  181479.1217
7      27  181479.1217
8      31  181479.1217
9      36  181479.1217
10     39  181479.1217
11     40  181479.1217
12     42  181479.1217
13     46  181479.1217
14     53  181479.1217
15     58  181479.1217
16     61  181479.1217
17     72  181479.1217
18     79  181479.1217
19     80  181479.1217
20     82  181479.1217
21     83  181479.1217
22     85  181479.1217
23     88  181479.1217
24     92  181479.1217
25     93  181479.1217
26     95  181479.1217
27    102  181479.1217
28    103  181479.1217
29    106  181479.1217
..    ...          ...
849  2825  181479.1217
850  2828  181479.1217
851  2831  181479.1217
852  2843  181479.1217
853  2845  181479.1217
854  2847  181479.1217
855  2855  181479.1217
856  2856  181479.1217
857  2859  181479.1217
858  2865  181479.1217
859  2867  181479.1217
860  2869  181479.1217
861  2870  181479.1217
862  2874  181479.1217
863  2876  181479.1217
864  2889  181479.1217
865  2892  181479.1217
866  2895  181479.1217
867  2898  181479.1217
868  2901  181479.1217
869  2902  181479.1217
870  2908  181479.1217
871  2909  181479.1217
872  2916  181479.1217
873  2917  181479.1217
874  2919  181479.1217
875  2921  181479.1217
876  2922  181479.1217
877  2925  181479.1217
878  2928  181479.1217

[879 rows x 2 columns]